Repository googleapis/java-firestore, pull requests merged in 2020-08, with the labels that each got.

#202 feat!: add support for the Query Partition API
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/QueryPartition.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/FirestoreRpc.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#317 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#321 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#315 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /firestore
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ListenDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/References.java
  samples/snippets/src/main/java/com/example/firestore/snippets/RetrieveDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/model/City.java
  samples/snippets/src/test/java/com/example/firestore/BaseIntegrationTest.java
  samples/snippets/src/test/java/com/example/firestore/QuickstartIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/ListenDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/RetrieveDataSnippetsIT.java
Labels: cla: no

#326 chore: cleanup of leftover remnants of Timestamps in Snapshots
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Labels: automerge, cla: yes

#325 fix: refactor FakeCredentials
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Labels: cla: yes

#327 chore(build): cleanup manually set api-commons version
  pom.xml
Labels: cla: yes

#328 chore: regenerate README.md with new samples section
  README.md
  synth.metadata
Labels: cla: yes, context: none

#320 feat: add support for read-only transactions in TransactionOptions
  google-cloud-firestore/pom.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#329 chore(build): add maven profile to enable samples
  pom.xml
Labels: cla: yes

#330 chore: make BulkWriter package-private
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#334 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#335 chore: regenerate README.md
  README.md
  synth.metadata
Labels: cla: yes, context: none

#339 chore(java_templates): add lint/static analysis presubmit checks for samples
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#341 chore: fix URLs found in POM files changed to match typical repository URL format
  google-cloud-firestore-admin/pom.xml
  google-cloud-firestore/pom.xml
Labels: automerge, cla: yes

#344 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#346 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#337 fix: add support to deserialize to custom Lists and Maps
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#348 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#347 fix(samples): re-add maven exec config for Quickstart sample
  samples/snippets/pom.xml
Labels: api: firestore, cla: yes

#336 feat: add method to set emulator host programmatically (#319)
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Labels: api: firestore, automerge, cla: yes
