Repository googleapis/java-firestore, pull requests merged in 2020-10, with the labels that each got.

#394 fix: bulkWriter: writing to the same doc doesn't create a new batch
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BatchWriteResult.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, cla: yes

#395 chore: add @googleapis/api-firestore to codeowner_team
  .repo-metadata.json
Labels: automerge, cla: yes

#398 chore: regenerate CODEOWNERS file
  .github/CODEOWNERS
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#399 chore: fix typo in test
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#404 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#406 chore: Remove update.sh and generate bundle.proto code from googleapis
  README.md
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundleElement.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundleElementOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundleMetadata.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundleMetadataOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundleProto.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundledDocumentMetadata.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundledDocumentMetadataOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundledQuery.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/BundledQueryOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/NamedQuery.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/bundle/NamedQueryOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleProto.java
  synth.metadata
  synth.py
  update.sh
Labels: api: firestore, cla: yes

#400 feat: add max/min throttling options to BulkWriterOptions
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/RateLimiter.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/RateLimiterTest.java
Labels: api: firestore, cla: yes

#408 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes

#407 feat: add bundle.proto from googleapis/googleapis
  proto-google-cloud-firestore-bundle-v1/src/main/proto/google/firestore/bundle/bundle.proto
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#419 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#420 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#423 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#422 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, cla: yes

#293 feat: Implementation of Firestore Bundle Builder
  google-cloud-firestore-bom/pom.xml
  google-cloud-firestore/pom.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreBundleTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
  pom.xml
Labels: api: firestore, automerge, cla: yes

#427 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#432 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#433 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#435 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#426 fix: retry Query streams
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
Labels: api: firestore, cla: yes

#436 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#418 fix: verify page count before invoking QueryPartition RPC
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#417 feat: add implicit ordering for startAt(DocumentReference) calls
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#438 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#440 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#441 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#443 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#445 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
