Repository googleapis/java-firestore, pull requests merged in 2020-07, with the labels that each got.

#283 build: remove unnecessary objenesis ignore rule
  pom.xml
Labels: cla: yes

#284 chore: release v1.35.1
  CHANGELOG.md
  README.md
  google-cloud-firestore-bom/pom.xml
  google-cloud-firestore/pom.xml
  grpc-google-cloud-firestore-admin-v1/pom.xml
  grpc-google-cloud-firestore-v1/pom.xml
  grpc-google-cloud-firestore-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-firestore-admin-v1/pom.xml
  proto-google-cloud-firestore-v1/pom.xml
  proto-google-cloud-firestore-v1beta1/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#292 fix: expose FirestoreImpl.autoId() for use in frameworks
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Internal.java
Labels: cla: yes

#295 fix: add support for deleting nested fields that contain periods
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BasePath.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#296 fix: use test credentials when connecting to the Emulator from Admin SDK
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Labels: cla: yes

#306 chore: update synthconfig to include generation of README.md
  .repo-metadata.json
  README.md
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#308 chore!: remove deprecated FirestoreOptions#setTimestampsInSnapshotsEnabled
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
Labels: automerge, cla: yes

#310 chore: regenerate README and add file tracking to synth.metadata
  README.md
  synth.metadata
Labels: cla: yes, context: none

#312 test: add junit timeout rule to BulkWriterTest
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: cla: yes

#313 build: add cloud-RAD for Java
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full
