Repository googleapis/java-firestore, pull requests merged in 2020-09, with the labels that each got.

#358 chore: regenerate readme.md
  README.md
  synth.metadata
Labels: cla: yes, context: none

#350 feat: add support for != and NOT_IN queries
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#360 feat: add opencensus tracing support
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TraceUtil.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
Labels: api: firestore, cla: yes

#363 chore: regenerate README.md
  README.md
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#366 chore: regenerate README.md
  README.md
  synth.metadata
Labels: cla: yes, context: none

#271 feat: Add bundle proto building
  pom.xml
  proto-google-cloud-firestore-bundle-v1/pom.xml
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleElement.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleElementOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleMetadata.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleMetadataOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundleProto.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundledDocumentMetadata.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundledDocumentMetadataOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundledQuery.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/BundledQueryOrBuilder.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/NamedQuery.java
  proto-google-cloud-firestore-bundle-v1/src/main/java/com/google/firestore/proto/NamedQueryOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/proto/firestore/BUILD.bazel
  proto-google-cloud-firestore-v1/src/main/proto/firestore/bundle.proto
  synth.metadata
  synth.py
  update.sh
Labels: api: firestore, cla: yes

#368 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#377 chore: exclude Bundle Proto from Synthtool run
  synth.py
Labels: api: firestore, cla: yes

#385 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: firestore, cla: yes

#384 chore: regenerate github config
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#388 chore: regenerate README.md
  README.md
  synth.metadata
Labels: cla: yes, context: none

#390 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#372 samples: add new samples for != and NOT IN queries
  samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
Labels: api: firestore, cla: yes, samples

#391 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#393 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
