Repository googleapis/java-firestore, pull requests merged in 2020-03, with the labels that each got.

#107 fix: deflake-ify ITSystemTest#queryWatch
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#119 chore: regenerate firestore protos
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestoreImpl.java
  grpc-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/FirestoreGrpc.java
  proto-google-cloud-firestore-v1/clirr-ignored-differences.xml
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/FirestoreProto.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/QueryProto.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/StructuredQuery.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Write.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/WriteOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/WriteProto.java
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/common.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/document.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/firestore.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/query.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/write.proto
  synth.metadata
Labels: cla: yes

#130 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: automerge, cla: yes

#137 chore: use java helper for templates
  synth.py
Labels: automerge, cla: yes

#140 samples: add scaffold
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
Labels: automerge, cla: yes

#103 feat: add new Firestore.runAsyncTransaction
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
Labels: cla: yes, semver: minor

#141 fix: add missing @InternalExtensionOnly annotation to com.google.cloud.firestore.Firestore
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
Labels: cla: yes

#143 chore: add clirr-ignored-differences.xml for new runAsyncTransaction methods added to Firestore
  google-cloud-firestore/clirr-ignored-differences.xml
Labels: cla: yes

#147 chore: enable context aware commits
  synth.py
Labels: automerge, cla: yes

#149 chore: update common templates
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/linkage-monitor.sh
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#150 chore: update renovate config for shared samples parent
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#145 chore: Migrate firestore synth.py to bazel
  grpc-google-cloud-firestore-admin-v1/clirr-ignored-differences.xml
  grpc-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FirestoreAdminGrpc.java
  grpc-google-cloud-firestore-v1/clirr-ignored-differences.xml
  grpc-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/FirestoreGrpc.java
  grpc-google-cloud-firestore-v1beta1/clirr-ignored-differences.xml
  grpc-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/FirestoreGrpc.java
  synth.py
Labels: automerge, cla: yes

#151 feat: add Query.limitToLast()
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#154 fix: mark v1beta1 as deprecated
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/FirestoreClient.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/FirestoreSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/package-info.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/FirestoreStub.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/FirestoreStubSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/GrpcFirestoreCallableFactory.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/GrpcFirestoreStub.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/FirestoreClientTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/MockFirestore.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/MockFirestoreImpl.java
  synth.metadata
  synth.py
Labels: cla: yes

#136 fix: add support for updating an individual field with pojo in all update method
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#156 feat: use SecureRandom instead of Random to reduce the chance of auto-id collisions
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
Labels: cla: yes
