Repository googleapis/java-firestore, pull requests merged in 2020-11, with the labels that each got.

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#453 docs(sample): normalize firestore sample's region tags
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ListenDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/References.java
  samples/snippets/src/main/java/com/example/firestore/snippets/RetrieveDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/model/City.java
Labels: api: firestore, cla: yes

#447 fix: retry transactions that fail with expired transaction IDs
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
Labels: api: firestore, cla: yes

#450 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#456 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#459 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#464 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#457 fix(build): sample checkstyle violations
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/References.java
  samples/snippets/src/test/java/com/example/firestore/QuickstartIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
Labels: api: firestore, cla: yes

#465 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#470 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#468 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#472 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#473 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#475 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full, samples
