Repository googleapis/java-firestore, pull requests merged in 2020-12, with the labels that each got.

#466 feat: Release bundles
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#482 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#484 chore: add .DS_Store to .gitignore
  .gitignore
Labels: api: firestore, cla: yes

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#490 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#492 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full, merge
