Repository googleapis/java-firestore, pull requests merged in 2021-07, with the labels that each got.

#687 chore: modify sample region tag to more closely match others
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
Labels: api: firestore, cla: yes, samples

#688 fix: lower batch size on BulkWriter retry
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, cla: yes

#668 chore: create flakybot.yaml
  .github/flakybot.yaml
Labels: api: firestore, cla: yes

#690 chore: remove distributionManagement section
  pom.xml
Labels: api: firestore, automerge, cla: yes

#692 chore: remove distributionManagement section
  google-cloud-firestore-bom/pom.xml
Labels: api: firestore, automerge, cla: yes

#695 fix: Ensures bundles are encoded as UTF8 bytes.
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
Labels: api: firestore, cla: yes

#694 fix: Update dependencies.sh to not break on mac
  .kokoro/coerce_logs.sh
  .kokoro/dependencies.sh
  java.header
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#683 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#697 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#696 docs: began merging variant client samples
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
Labels: api: firestore, cla: yes, samples

#698 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#699 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#691 chore(samples): remove old region tags
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
Labels: api: firestore, cla: yes, samples

#701 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#666 chore: release gapic-generator-java v1.0.11
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreClientTest.java
  synth.metadata
Labels: api: firestore, cla: yes, context: full
