Repository googleapis/java-firestore, pull requests merged in 2021-02, with the labels that each got.

#517 chore: update LICENSE formatting
  LICENSE
Labels: api: firestore, cla: yes

#522 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  LICENSE
  synth.metadata
Labels: api: firestore, cla: yes, context: partial

#526 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#527 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#528 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#523 chore: simplify BulkWriter
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOperation.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/WriteBatch.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, automerge, cla: yes

#533 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#532 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#534 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#476 fix(samples): close firestore instance in test
  samples/snippets/src/main/java/com/example/firestore/Quickstart.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ListenDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  samples/snippets/src/main/java/com/example/firestore/snippets/RetrieveDataSnippets.java
  samples/snippets/src/test/java/com/example/firestore/BaseIntegrationTest.java
  samples/snippets/src/test/java/com/example/firestore/QuickstartIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/ListenDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
  samples/snippets/src/test/java/com/example/firestore/snippets/RetrieveDataSnippetsIT.java
Labels: api: firestore, cla: yes, samples

#529 chore: fix some potential threading issues in BulkWriter
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOperation.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, cla: yes

#512 fix: block close() on the termination of all RPC channels
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
Labels: api: firestore, cla: yes

#536 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#537 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#538 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#539 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#545 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#548 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#549 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#552 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#558 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes
