Repository googleapis/java-firestore, pull requests merged in 2021-08, with the labels that each got.

#713 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: firestore, automerge, cla: yes

#714 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: firestore, automerge, cla: yes

#707 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#712 feat: gapic-generator-java v1.0.13, mtls support
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStubSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStubSettings.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/CollectionGroupName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/DatabaseName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FieldName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/IndexName.java
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#721 build: remove java 7 as required check for main branch
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: firestore

#720 deps: update shared dependencies to 2.0.0
  pom.xml
Labels: cla: yes, api: firestore

#719 feat!: update gapic generator to 2.0.0, java 8 features
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminClient.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStubSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminStub.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStubSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#703 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#722 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#727 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#732 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#726 chore: hello Java8
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSet.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldMask.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldPath.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Internal.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/RecursiveDelete.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/ArraySortedMap.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/ImmutableSortedMap.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/ImmutableSortedMapIterator.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/ImmutableSortedSet.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/LLRBBlackValueNode.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/LLRBEmptyNode.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/LLRBNode.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/LLRBRedValueNode.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/LLRBValueNode.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/RBTreeSortedMap.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/collection/StandardComparator.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/CollectionReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceConversions.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreBundleTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/ITBulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/MapperTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITShutdownTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes, api: firestore

#733 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#737 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#738 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#744 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: firestore

#745 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#748 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge

#752 deps: update google-cloud-conformance-tests to 0.2.0
  google-cloud-firestore/pom.xml
Labels: cla: yes, api: firestore, automerge

#755 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: firestore, automerge
