Repository googleapis/java-firestore, pull requests merged in 2021-03, with the labels that each got.

#560 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#564 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#565 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#569 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#508 Removed Jackson dependency
  google-cloud-firestore/pom.xml
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/MapperTest.java
Labels: api: firestore, cla: yes

#573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#575 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: firestore, build.sh, cla: yes, context: full, in, sample-secrets, samples

#577 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full
