Repository googleapis/java-firestore, pull requests merged in 2021-04, with the labels that each got.

#578 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#589 test: Update assertion in failing test: ITSystemTest.readOnlyTransaction_failureWhenAttemptReadOlderThan60Seconds
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#580 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#587 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#590 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#595 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#593 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#599 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#600 feat: add backoff to BulkWriter
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOperation.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, cla: yes

#611 feat: add buffering layer to BulkWriter
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Labels: api: firestore, cla: yes

#605 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes, kokoro:force-run

#613 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes
