Repository googleapis/java-firestore, pull requests merged in 2021-05, with the labels that each got.

#615 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: none

#625 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#629 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#630 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#631 fix: add flush check in BulkWriter.sendBatchLocked() callback
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
Labels: api: firestore, cla: yes

#562 chore: migrate firestore to the Java microgenerator
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminClient.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/gapic_metadata.json
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/package-info.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStub.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStubSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminCallableFactory.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminStub.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/MockFirestoreAdmin.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/MockFirestoreAdminImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/gapic_metadata.json
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/package-info.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStub.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStubSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreCallableFactory.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreClientTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestore.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestoreImpl.java
  proto-google-cloud-firestore-admin-v1/clirr-ignored-differences.xml
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/CollectionGroupName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/DatabaseName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FieldName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/Index.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/IndexName.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/BatchGetDocumentsRequest.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/BatchGetDocumentsRequestOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/BatchGetDocumentsResponse.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/BatchGetDocumentsResponseOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentTransform.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/GetDocumentRequest.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/GetDocumentRequestOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/ListDocumentsRequest.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/ListDocumentsRequestOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/ListenRequest.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/ListenRequestOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Precondition.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/PreconditionOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/RunQueryRequest.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/RunQueryRequestOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Target.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/TargetOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Value.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/ValueOrBuilder.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Write.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/WriteOrBuilder.java
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#633 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#634 chore: regen with latest microgenerator version (1.0.2)
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminClient.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/package-info.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStub.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreAdminStubSettings.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminCallableFactory.java
  google-cloud-firestore-admin/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminStub.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/MockFirestoreAdmin.java
  google-cloud-firestore-admin/src/test/java/com/google/cloud/firestore/v1/MockFirestoreAdminImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/package-info.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStub.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStubSettings.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreCallableFactory.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreClientTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestore.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestoreImpl.java
  grpc-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FirestoreAdminGrpc.java
  grpc-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/FirestoreGrpc.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/CollectionGroupName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/DatabaseName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FieldName.java
  proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/IndexName.java
  proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentTransform.java
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/common.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/document.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/firestore.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/query.proto
  proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/write.proto
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#635 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#638 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#639 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#641 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#646 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#622 feat: add recursiveDelete() to Firestore
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/RecursiveDelete.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#649 feat: add recursiveDelete() to Firestore
  google-cloud-firestore/clirr-ignored-differences.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/RecursiveDelete.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#643 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes

#654 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: firestore, automerge, cla: yes
