Repository googleapis/java-firestore, pull requests merged in 2021-09, with the labels that each got.

#746 chore: enable release-trigger bot
  .github/release-trigger.yml
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#764 chore: regenerate common templates
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, api: firestore, automerge, context: full

#763 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: firestore, automerge

#779 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#781 chore: Re-generated to pick up changes from synthtool
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#784 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, api: firestore, automerge

#783 chore: fix doc generation
  pom.xml
Labels: cla: yes, api: firestore
