Repository googleapis/java-firestore, pull requests merged in 2022-01, with the labels that each got.

#847 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: api: firestore, automerge, owlbot:ignore

#853 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: api: firestore, owlbot:ignore

#838 chore: re-generated to pick up changes from synthtool
  .kokoro/build.sh
  synth.metadata
Labels: api: firestore, context: full

#855 chore: cleanup cloud rad gen profile
  pom.xml
Labels: api: firestore

#834 fix: close the Watch stream when we receive an error
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/PartitionQuery.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
Labels: api: firestore
