Repository googleapis/java-firestore, pull requests merged in 2024-07, with the labels that each got.

#1727 chore: correct hermetic library generation script path
  .github/workflows/hermetic_library_generation.yaml
Labels: api: firestore, size: xs

#1730 chore: skip hermetic generation on fork PRs
  .github/workflows/hermetic_library_generation.yaml
Labels: api: firestore, size: xs

#1732 chore: make the owlbot postprocessor check non-required
  .github/sync-repo-settings.yaml
Labels: kokoro:run, api: firestore, automerge, size: xs

#1731 chore: disable the Owl Bot post-processor
  .github/.OwlBot.lock.yaml
Labels: api: firestore, size: s

#1728 feat: Tracing using OpenTelemetry
  README.md
  google-cloud-firestore/pom.xml
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOpenTelemetryOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ReadTimeTransaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ServerSideTransaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/ServerSideTransactionRunner.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/TraceUtil.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/telemetry/DisabledTraceUtil.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/telemetry/EnabledTraceUtil.java
  google-cloud-firestore/src/main/java/com/google/cloud/firestore/telemetry/TraceUtil.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/OpenTelemetryOptionsTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITE2ETracingTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITE2ETracingTestGlobalOtel.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITE2ETracingTestNonGlobalOtel.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITTracingTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITTracingTestGlobalOtel.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITTracingTestNonGlobalOtel.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/telemetry/DisabledTraceUtilTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/telemetry/EnabledTraceUtilTest.java
  google-cloud-firestore/src/test/java/com/google/cloud/firestore/telemetry/TraceUtilTest.java
  google-cloud-firestore/src/test/resources/META-INF/native-image/reflect-config.json
Labels: api: firestore, size: xl

#1733 chore: remove native image sample in favor of sample hosted in google-cloud-java
  README.md
  samples/native-image-sample/README.md
  samples/native-image-sample/pom.xml
  samples/native-image-sample/src/main/java/com/example/firestore/NativeImageFirestoreSample.java
  samples/native-image-sample/src/main/java/com/example/firestore/Person.java
  samples/native-image-sample/src/main/resources/META-INF/native-image/reflect-config.json
  samples/native-image-sample/src/test/java/com/example/firestore/ITNativeImageFirestoreSample.java
  samples/pom.xml
Labels: api: firestore, samples, size: l
